FROM arm32v7/python:3.5-stretch

USER root

# install OpenCV: https://www.pyimagesearch.com/2017/09/04/raspbian-stretch-install-opencv-3-python-on-your-raspberry-pi/
RUN apt-get -y update && apt-get -y upgrade && \
    apt-get -y install zip unzip build-essential cmake pkg-config && \
    apt-get -y install libjpeg-dev libpng-dev libtiff-dev && \
    apt-get -y install libavcodec-dev libavformat-dev libswscale-dev libv4l-dev && \
    apt-get -y install libxvidcore-dev libx264-dev && \
    apt-get -y install libgtk2.0-dev libgtk-3-dev && \
    apt-get -y install libatlas-base-dev gfortran && \
#    apt-get -y install python3-dev && \
    cd /tmp && wget -O opencv.zip https://github.com/Itseez/opencv/archive/3.4.1.zip && unzip opencv.zip && rm opencv.zip && \
    wget -O opencv_contrib.zip https://github.com/Itseez/opencv_contrib/archive/3.4.1.zip && unzip opencv_contrib.zip && rm opencv_contrib.zip && \
    pip install numpy && \
    cd /tmp/opencv-3.4.1/ && mkdir build && cd build && cmake -D CMAKE_BUILD_TYPE=RELEASE \
        -D CMAKE_INSTALL_PREFIX=/usr/local \
        -D INSTALL_PYTHON_EXAMPLES=ON \
        -D OPENCV_EXTRA_MODULES_PATH=/tmp/opencv_contrib-3.4.1/modules \
        -D BUILD_EXAMPLES=ON .. && \
    make -j4 && make install && ldconfig && \
    cd /usr/local/lib/python3.5/site-packages/ && mv cv2.cpython-35m-arm-linux-gnueabihf.so cv2.so
